import { extendTheme } from "@chakra-ui/react";

import { Button } from "./components/button";
import { Input } from "./components/input";
import { Link } from "./components/link";

const breakpoints = {
  sm: '388px',
  md: '768px',
  lg: '960px',
  xl: '1200px',
  '2xl': '1536px',
}

const theme = extendTheme({
  breakpoints,
  components: {
    Button, 
    Input, 
    Link,
  },
  
  fonts: {
    heading: 'Figtree',
    body: 'Figtree'
  },
  sizes: {
    container: {
      sm: '960px',
      md: '1040px',
      lg: '1160px',
      xl: '1280px',
      xxl: '1600px',
    },
  },
  colors: {
    primary: {
      0: '#000000',
      4: '#00110E',
      10: '#00201b',
      12: '#04241F',
      17: '#102F2A',
      20: '#00201b',
      22: '#173630',
      25: '#00443a',
      30: '#005046',
      35: '#005d51',
      40: '#006b5d',
      50: '#008675',
      60: '#00a38e',
      70: '#32bfa9',
      80: '#57dbc4',
      90: '#77f8e0',
      92: '#7DFEE5',
      94: '#A3FFEB',
      95: '#b6ffee',
      96: '#C7FFF1',
      98: '#e5fff7',
      99: '#f3fffa',
      100: '#ffffff',
    },
    secondary: {
      0: '#000000',
      4: '#00110D',
      10: '#06201b',
      12: '#0A241F',
      17: '#152E29',
      20: '#1c3530',
      22: '#213934',
      25: '#28403b',
      30: '#334b46',
      35: '#3e5751',
      40: '#4a635d',
      50: '#637c76',
      60: '#7c968f',
      70: '#96b1aa',
      80: '#b1ccc5',
      90: '#cde8e0',
      92: '#D2EEE6',
      94: '#D8F4EC',
      95: '#dbf7ef',
      96: '#DEFAF2',
      98: '#e5fff7',
      99: '#f3fffa',
      100: '#ffffff',
    },
    tertiary: {
      0: '#000000',
      10: '#001e2f',
      20: '#123348',
      25: '#1f3e54',
      30: '#2b4a60',
      35: '#38566c',
      40: '#446278',
      50: '#5c7a92',
      60: '#7694ad',
      70: '#90afc8',
      80: '#abcae5',
      90: '#c9e6ff',
      95: '#e6f2ff',
      98: '#f6faff',
      99: '#fcfcff',
      100: '#ffffff',
    },
    neutral: {
      0: '#000000',
      4: '#0C0F0E',
      10: '#191c1b',
      12: '#1D201F',
      17: '#282B29',
      20: '#2d3130',
      22: '#323534',
      25: '#393c3b',
      30: '#444746',
      35: '#505352',
      40: '#5c5f5d',
      50: '#747876',
      60: '#8e918f',
      70: '#a9acaa',
      80: '#c4c7c5',
      90: '#e0e3e1',
      92: '#E6E9E7',
      94: '#ECEEEC',
      95: '#eff1ef',
      96: '#F1F4F2',
      98: '#f8faf7',
      99: '#fafdfa',
      100: '#ffffff',
      },
    neutralVariant: {
      0: '#000000',
      4: '#07100E',
      10: '#141d1b',
      12: '#18211F',
      17: '#232C2A',
      20: '#293230',
      22: '#2D3734', 
      25: '#343d3b',
      30: '#3f4946',
      35: '#4b5452',
      40: '#57605d',
      50: '#6f7976',
      60: '#89938f',
      70: '#a3adaa',
      80: '#bec9c5',
      90: '#dae5e1',
      92: '#e0eae6',
      94: '#e6f0ec',
      95: '#e9f3ef',
      96: '#ecf6f2',
      98: '#f1fcf7',
      99: '#f4fffa',
      100: '#ffffff',
      },
    neutralWhite: {
      'background': 'var(--chakra-colors-neutral-100)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-neutral-100)',
      'surface-low': 'var(--chakra-colors-neutral-96)',
      'surface': 'var(--chakra-colors-neutral-94)',
      'surface-high': 'var(--chakra-colors-neutral-92)',
      'surface-highest': 'var(--chakra-colors-neutral-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'outline': 'var(--chakra-colors-neutralVariant-50)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralLight: {
      'background': 'var(--chakra-colors-neutral-98)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-neutral-100)',
      'surface-low': 'var(--chakra-colors-neutral-96)',
      'surface': 'var(--chakra-colors-neutral-94)',
      'surface-high': 'var(--chakra-colors-neutral-92)',
      'surface-highest': 'var(--chakra-colors-neutral-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'outline': 'var(--chakra-colors-neutralVariant-50)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralDark: {
      'background': 'var(--chakra-colors-neutral-4)',
      'on-background': 'var(--chakra-colors-neutral-90)',
      'surface-lowest': 'var(--chakra-colors-neutral-0)',
      'surface-low': 'var(--chakra-colors-neutral-10)',
      'surface': 'var(--chakra-colors-neutral-12)',
      'surface-high': 'var(--chakra-colors-neutral-17)',
      'surface-highest': 'var(--chakra-colors-neutral-22)',
      'on-surface': 'var(--chakra-colors-neutral-90)',
      'outline': 'var(--chakra-colors-neutralVariant-40)',
      'primary': 'var(--chakra-colors-primary-70)'
    },
    neutralVariantWhite: {
      'background': 'var(--chakra-colors-neutralVariant-100)',
      'on-background': 'var(--chakra-colors-neutralVariant-10)',
      'surface-lowest': 'var(--chakra-colors-neutralVariant-100)',
      'surface-low': 'var(--chakra-colors-neutralVariant-96)',
      'surface': 'var(--chakra-colors-neutralVariant-94)',
      'surface-high': 'var(--chakra-colors-neutralVariant-92)',
      'surface-highest': 'var(--chakra-colors-neutralVariant-90)',
      'on-surface': 'var(--chakra-colors-neutralVariant-10)',
      'outline': 'var(--chakra-colors-neutralVariantVariant-50)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralVariantLight: {
      'background': 'var(--chakra-colors-neutralVariant-98)',
      'on-background': 'var(--chakra-colors-neutralVariant-10)',
      'surface-lowest': 'var(--chakra-colors-neutralVariant-100)',
      'surface-low': 'var(--chakra-colors-neutralVariant-96)',
      'surface': 'var(--chakra-colors-neutralVariant-94)',
      'surface-high': 'var(--chakra-colors-neutralVariant-92)',
      'surface-highest': 'var(--chakra-colors-neutralVariant-90)',
      'on-surface': 'var(--chakra-colors-neutralVariant-10)',
      'outline': 'var(--chakra-colors-neutralVariant-50)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    neutralVariantDark: {
      'background': 'var(--chakra-colors-neutralVariant-4)',
      'on-background': 'var(--chakra-colors-neutralVariant-90)',
      'surface-lowest': 'var(--chakra-colors-neutralVariant-0)',
      'surface-low': 'var(--chakra-colors-neutralVariant-10)',
      'surface': 'var(--chakra-colors-neutralVariant-12)',
      'surface-high': 'var(--chakra-colors-neutralVariant-17)',
      'surface-highest': 'var(--chakra-colors-neutralVariant-22)',
      'on-surface': 'var(--chakra-colors-neutralVariant-90)',
      'outline': 'var(--chakra-colors-neutralVariantVariant-40)',
      'primary': 'var(--chakra-colors-primary-70)'
    },
    primaryWhite: {
      'background': 'var(--chakra-colors-primary-100)',
      'on-background': 'var(--chakra-colors-primary-20)',
      'surface-lowest': 'var(--chakra-colors-primary-100)',
      'surface-low': 'var(--chakra-colors-primary-96)',
      'surface': 'var(--chakra-colors-primary-94)',
      'surface-high': 'var(--chakra-colors-primary-92)',
      'surface-highest': 'var(--chakra-colors-primary-90)',
      'on-surface': 'var(--chakra-colors-primary-20)',
      'container': 'var(--chakra-colors-primary-95)',
      'outline': 'var(--chakra-colors-neutral-70)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    primaryLight: {
      'background': 'var(--chakra-colors-primary-99)',
      'on-background': 'var(--chakra-colors-primary-30)',
      'surface-lowest': 'var(--chakra-colors-primary-100)',
      'surface-low': 'var(--chakra-colors-primary-96)',
      'surface': 'var(--chakra-colors-primary-94)',
      'surface-high': 'var(--chakra-colors-primary-92)',
      'surface-highest': 'var(--chakra-colors-primary-90)',
      'on-surface': 'var(--chakra-colors-primary-30)',
      'container': 'var(--chakra-colors-primary-95)',
      'outline': 'var(--chakra-colors-neutral-60)',
      'primary': 'var(--chakra-colors-primary-70)',
    },
    primaryDark: {
      'background': 'var(--chakra-colors-primary-4)',
      'on-background': 'var(--chakra-colors-primary-98)',
      'surface-lowest': 'var(--chakra-colors-primary-0)',
      'surface-low': 'var(--chakra-colors-primary-10)',
      'surface': 'var(--chakra-colors-primary-12)',
      'surface-high': 'var(--chakra-colors-primary-17)',
      'surface-highest': 'var(--chakra-colors-primary-22)',
      'on-surface': 'var(--chakra-colors-primary-98)',
      'outline': 'var(--chakra-colors-primaryVariant-40)',
      'primary': 'var(--chakra-colors-primary-70)'
    },
    secondaryWhite: {
      'background': 'var(--chakra-colors-secondary-100)',
      'on-background': 'var(--chakra-colors-neutral-30)',
      'surface-lowest': 'var(--chakra-colors-secondary-100)',
      'surface-low': 'var(--chakra-colors-secondary-96)',
      'surface': 'var(--chakra-colors-secondary-94)',
      'surface-high': 'var(--chakra-colors-secondary-92)',
      'surface-highest': 'var(--chakra-colors-secondary-90)',
      'on-surface': 'var(--chakra-colors-neutral-30)',
      'container': 'var(--chakra-colors-secondary-95)',
      'primary': 'var(--chakra-colors-secondary-70)',
    },
    secondaryLight: {
      'background': 'var(--chakra-colors-secondary-99)',
      'on-background': 'var(--chakra-colors-secondary-30)',
      'surface-lowest': 'var(--chakra-colors-secondary-100)',
      'surface-low': 'var(--chakra-colors-secondary-96)',
      'surface': 'var(--chakra-colors-secondary-94)',
      'surface-high': 'var(--chakra-colors-secondary-92)',
      'surface-highest': 'var(--chakra-colors-secondary-90)',
      'on-surface': 'var(--chakra-colors-secondary-30)',
      'container': 'var(--chakra-colors-secondary-95)',
      'primary': 'var(--chakra-colors-secondary-70)',
    },
    secondaryDark: {
      'background': 'var(--chakra-colors-secondary-4)',
      'on-background': 'var(--chakra-colors-secondary-90)',
      'surface-lowest': 'var(--chakra-colors-secondary-0)',
      'surface-low': 'var(--chakra-colors-secondary-10)',
      'surface': 'var(--chakra-colors-secondary-12)',
      'surface-high': 'var(--chakra-colors-secondary-17)',
      'surface-highest': 'var(--chakra-colors-secondary-22)',
      'on-surface': 'var(--chakra-colors-secondary-95)',
      'outline': 'var(--chakra-colors-secondaryVariant-40)',
      'primary': 'var(--chakra-colors-secondary-70)'
    },
    tertiaryWhite: {
      'background': 'var(--chakra-colors-tertiary-100)',
      'on-background': 'var(--chakra-colors-neutral-10)',
      'surface-lowest': 'var(--chakra-colors-tertiary-100)',
      'surface-low': 'var(--chakra-colors-tertiary-96)',
      'surface': 'var(--chakra-colors-tertiary-94)',
      'surface-high': 'var(--chakra-colors-tertiary-92)',
      'surface-highest': 'var(--chakra-colors-tertiary-90)',
      'on-surface': 'var(--chakra-colors-neutral-10)',
      'container': 'var(--chakra-colors-tertiary-95)',
      'primary': 'var(--chakra-colors-tertiary-70)',
    },
    tertiaryLight: {
      'background': 'var(--chakra-colors-tertiary-98)',
      'on-background': 'var(--chakra-colors-tertiary-10)',
      'surface-lowest': 'var(--chakra-colors-tertiary-100)',
      'surface-low': 'var(--chakra-colors-tertiary-96)',
      'surface': 'var(--chakra-colors-tertiary-94)',
      'surface-high': 'var(--chakra-colors-tertiary-92)',
      'surface-highest': 'var(--chakra-colors-tertiary-90)',
      'on-surface': 'var(--chakra-colors-tertiary-10)',
      'container': 'var(--chakra-colors-tertiary-95)',
      'primary': 'var(--chakra-colors-tertiary-70)',
    },
    tertiaryDark: {
      'background': 'var(--chakra-colors-tertiary-4)',
      'on-background': 'var(--chakra-colors-tertiary-90)',
      'surface-lowest': 'var(--chakra-colors-tertiary-0)',
      'surface-low': 'var(--chakra-colors-tertiary-10)',
      'surface': 'var(--chakra-colors-tertiary-12)',
      'surface-high': 'var(--chakra-colors-tertiary-17)',
      'surface-highest': 'var(--chakra-colors-tertiary-22)',
      'on-surface': 'var(--chakra-colors-tertiary-90)',
      'outline': 'var(--chakra-colors-tertiaryVariant-40)',
      'primary': 'var(--chakra-colors-tertiary-70)'
    },
  }
});

export default theme;
